# Generated by Django 5.0 on 2023-12-31 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_categorie_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voyage',
            old_name='ville',
            new_name='destination',
        ),
    ]
