# Generated by Django 5.0 on 2023-12-31 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_rename_ville_voyage_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voyage',
            old_name='categorie',
            new_name='category',
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.country')),
            ],
        ),
    ]
