# Generated by Django 5.0 on 2024-01-25 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_country_photo_destination_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.categorie'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.country'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.destination'),
        ),
    ]
