# Generated by Django 5.0 on 2024-02-02 10:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0008_alter_voyage_category_alter_voyage_country_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Avion",
        ),
    ]
