# Generated by Django 5.0 on 2024-02-02 11:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0010_avion"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Hotel",
        ),
    ]
