# Generated by Django 5.0 on 2024-02-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0011_delete_hotel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("hotelNom", models.CharField(max_length=200)),
                ("etoile", models.CharField(max_length=20)),
                (
                    "prixChambreSingle",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "prixChambreDouble",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "prixChambreSubTriple",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("prixEnfant", models.DecimalField(decimal_places=2, max_digits=18)),
                ("prixBebe", models.DecimalField(decimal_places=2, max_digits=18)),
            ],
        ),
    ]
