# Generated by Django 5.0 on 2024-02-02 11:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0012_hotel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Voyage",
        ),
    ]
