# Generated by Django 5.0 on 2024-02-02 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0013_delete_voyage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Voyage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("duration", models.IntegerField()),
                ("prix", models.DecimalField(decimal_places=2, max_digits=18)),
                ("description", models.TextField()),
                ("photo", models.ImageField(blank=True, null=True, upload_to="media/")),
                (
                    "avion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.hotel",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.destination",
                    ),
                ),
            ],
        ),
    ]
