# Generated by Django 5.0 on 2024-02-02 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0014_voyage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Voyage",
        ),
    ]
