# Generated by Django 5.0 on 2024-02-02 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0016_voyage"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="localisation",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="admin_panel.destination",
            ),
            preserve_default=False,
        ),
    ]
