# Generated by Django 5.0 on 2024-02-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_hotel_localisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='nombre_places',
            field=models.IntegerField(default=0),
        ),
    ]
