# Generated by Django 5.0 on 2024-02-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0018_voyage_nombre_places"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComptePayPal",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nomComplet", models.CharField(max_length=200, unique=True)),
                ("cardNumber", models.CharField(max_length=200, unique=True)),
                ("code", models.CharField(max_length=200, unique=True)),
                ("solde", models.DecimalField(decimal_places=2, max_digits=29)),
            ],
        ),
        migrations.CreateModel(
            name="PayPal",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nomComplet", models.CharField(max_length=200, unique=True)),
                ("cardNumber", models.CharField(max_length=200, unique=True)),
                ("code", models.CharField(max_length=200, unique=True)),
                ("solde", models.DecimalField(decimal_places=2, max_digits=29)),
            ],
        ),
        migrations.RemoveField(
            model_name="voyage",
            name="nombre_places",
        ),
    ]
