# Generated by Django 5.0 on 2024-02-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0021_comptevisa_reservation_delete_paypal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comptepaypal",
            name="code",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="comptevisa",
            name="code",
            field=models.CharField(max_length=200),
        ),
    ]
