# Generated by Django 5.0 on 2024-02-06 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0022_alter_comptepaypal_code_alter_comptevisa_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "pourcentagePromotion",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("nouveauPrix", models.DecimalField(decimal_places=2, max_digits=29)),
                ("dateDebut", models.DateField()),
                ("dateFin", models.DateField()),
                (
                    "voyage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.voyage",
                    ),
                ),
            ],
        ),
    ]
