# Generated by Django 5.0 on 2024-02-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0024_notificationclient"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationAdmin",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(default="", max_length=800)),
                ("voyage", models.CharField(default="", max_length=800)),
                ("client", models.CharField(default="", max_length=800)),
            ],
        ),
    ]
