# Generated by Django 5.0 on 2023-12-25 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0006_customuser_delete_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='Users',
        ),
    ]
