# Generated by Django 5.0 on 2023-12-25 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_users_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_admin',
        ),
    ]
