# Generated by Django 5.0 on 2024-02-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_users_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="adresse",
            field=models.CharField(default="", max_length=800),
        ),
    ]
